# See
# https://docs.haskellstack.org/en/stable/travis_ci/
# https://raw.githubusercontent.com/commercialhaskell/stack/master/doc/travis-simple.yml
sudo: false

language: generic

cache:
  directories:
  - $HOME/.stack

addons:
  apt:
    packages:
      - libgmp-dev

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
# Build dependencies
- stack --no-terminal --install-ghc build --only-dependencies

script:
- stack --no-terminal build
- stack exec -- formura test-src/sample.fmr
- ./diff-test.sh
